const os = require('os')

console.log(os.userInfo())
console.log(os.hostname())
console.log(os.arch())
console.log(os.platform())
console.log(os.version())
console.log(os.uptime() / 3600)
console.log(os.cpus().length)
console.log(os.totalmem() / (1024*1024*1024))